# fly.toml app configuration file generated for shems-server on 2023-12-20T12:09:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shems-server"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
